// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 6.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_fade(c,a,b){var e=jQuery,g=e(this),d=e(".ws_list",b),h={position:"absolute",left:0,top:0,width:"100%",height:"100%",transform:"translate3d(0,0,0)"},f=e("<div>").addClass("ws_effect").css(h).css("overflow","hidden").appendTo(b.parent());this.go=function(i,j){var k=e(a.get(i)),m={width:k.width(),height:k.height()};k=k.clone().css(h).css(m).hide().appendTo(f);if(!c.noCross){var l=e(a.get(j)).clone().css(h).css(m).appendTo(f);l.fadeOut(c.duration,function(){l.remove()})}k.fadeIn(c.duration,function(){g.trigger("effectEnd");k.remove()})}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 6.3
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container6").wowSlider({effect:"fade",prev:"",next:"",duration:46*100,delay:20*100,width:1024,height:184,autoPlay:true,autoPlayVideo:true,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:false,captionEffect:"move",controls:false,responsive:2,fullScreen:false,onBeforeStep:0,images:[{src:"./amarillo.jpg",title:"amarillo",descr:"SUMMER"},{src:"./azule.jpg",title:"azule",descr:"SUMMER"},{src:"./morado.jpg",title:"morado",descr:"SUMMER"},{src:"./rojo.jpg",title:"rojo",descr:"SUMMER"},{src:"./rosa.jpg",title:"rosa",descr:"SUMMER"},{src:"./verde.jpg",title:"verde",descr:"SUMMER"}]});